### PR TITLE
Fixes rummy reset functionality and removes What did you say from games (except rummy tutorial).

### PR DESCRIPTION
**Pull request by mbehrooz**
Notes:
1. There is a standing new bug caused by other core system parts, which is not a result of this pull request. >>>Update: Resolved and sync'ed
2. This changes AdjacencyPairBase and adds a small flag which by default has a value that does not affect the functionality of other plugins. You can set it to false to turn off what did you say button.
3. As a result of merging this, VS should be built again.
4. Fixes the bug that user could play two moves in a row in one turn very fast for both TTT and Checkers!
5. Improves locking in checkers, small timing improvements, cleanups, etc.

Thanks, 
Yours, 
Morteza

### CODE REVIEW

**Comment by charlesrich** [comment]
I do not understand comment 1 above?

**Comment by mbehrooz** [comment]
Hi, As I emailed you, as a result of updating from upstream, the agent cannot make comments now. By that I mean the proposed syncsaybuilder behavior inside GameSchema classes does not seem to be sccepted snymore. I made certain that this is not a change I did in my commits...

**Comment by charlesrich** [comment]
Do not know what changed.  Can you take a look at commits between your working and non-working versions and see what relevant changed?  Good GitHub practice :)

**Comment by mbehrooz** [comment]
Definitely, I will report back in a few hours! Positive side, I fixed both What did you say button and Rummy resetGame. Thanks :)

**Comment by mbehrooz** [comment]
Ok, so I figured it out finally as I emailed and it is not related to this pull. So it is safe for merge in future.

**Pull request merged**
